name: Bot Wen Instagram

on:
  schedule:
    - cron: '0 */5 * * *' # Roda a cada 5 horas
  workflow_dispatch: # Botão para rodar manual

permissions:
  contents: write

jobs:
  postar:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar bibliotecas
        run: pip install -r requirements.txt

      - name: Rodar o Robô
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}  # <--- ESSA LINHA FALTAVA!
        run: python robo.py

      - name: Salvar Arte no Git
        run: |
          git config --global user.name 'Wen Bot'
          git config --global user.email 'bot@wen.com'
          git add wen_art.jpg wen_art.txt
          git commit -m "Nova arte gerada" || exit 0
          git push
